#!/bin/sh

# @category install script
# @author Андрей Новиков <andrey@novikov.be>
# @data 07/12/2015

echo "Post-install scripting ..."
mkdir -p ./public/css
mkdir -p ./public/js
mkdir -p ./Application/view
cp ./vendor/bermud-ru/phproll/public/index.php ./public/
cp -n ./vendor/bermud-ru/phproll/config.php ./
cp -n ./vendor/bermud-ru/phproll/public/css/* ./public/css/
#cp -n ./vendor/bermud-ru/phproll/public/js/* ./public/js/
cp -n ./vendor/bermud-ru/phproll/Application/view/* ./Application/view/