#!/usr/bin/env bash
#
# @category Installation nginx with TLS 1.3 (CentOS 7.x, 8.x)
# @author Андрей Новиков <andrey@novikov.be>
# @data 07/12/2015
#

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

######## CONFIG ##########################################################################
export vendor=vendor/bermud-ru/phproll
export serverRoot=$(pwd)
export PROJECT=${PWD##*/}
export DOMAIN=$(jq .install.domain ./composer.json)
export ADDRESS=$(jq .install.address ./composer.json)
export SSL_path=$(pwd)/etc/pki
##########################################################################################

echo "Post-update scripting ..."
#cp ./vendor/bermud-ru/phproll/public/index.php ./public/
#cp -n ./vendor/bermud-ru/phproll/public/js/* ./public/js/
#for js in ./vendor/bermud-ru/phproll/public/js/*
#do
# [ -f $js ] && cp -n $js ./public/js/
#done

printf "WEB context resotre\n"
chcon -R -t httpd_sys_content_t $serverRoot
semanage fcontext -a -t httpd_sys_content_t "${serverRoot}/(/.*)?"

exit
