<style>
    [role="main"] {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
    [role="main"] div {
        margin: 10%;
    }
</style>

<main role="main" class="container">
    <div class="jumbotron" align="center">
        <h2>4<i class="fa fa-repeat"></i>3 У Вас не достаточно прав для дотупа к ресурсу!</h2>
        <p><a class="navbar-brand" href="javascript:void(window.location.href=window.location.href.match(/^(?:https?:\/\/)?(?:(?:[\w]+\.)(?:\.?[\w]{2,})+)/)[0])">Попробуте с начала.</a></p>
    </div>
</main>
